Do not retry on `error:`
Signed-off-by: Josh Soref <2119212+jsoref@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,8 +49,18 @@ jobs:
       env:
         GH_TOKEN: ${{ github.token }}
       shell: bash
-      run:  |
-        until dotnet nuget push 'build/output/*.nupkg' -k "$GH_TOKEN" --skip-duplicate --no-symbols true; do echo "Retrying"; sleep 1; done;
+      run: |
+        : publish to github package repository
+        log=$(mktemp)
+        message=$(mktemp)
+        until dotnet nuget push 'build/output/*.nupkg' -k "$GH_TOKEN" --skip-duplicate --no-symbols true | tee "$log"; do
+          if grep --color=always '^error:.*' "$log" > "$message"; then
+            echo "::error ::$(perl -pe 's/^error: //' "$message")"
+            exit 1
+          fi
+          echo "Retrying"
+          sleep 1
+        done
 
     - name: Generate release notes for tag
       if: github.event_name == 'push' && startswith(github.ref, 'refs/tags')
